### ISSUE TITLE
how to generate a alope units ?

### ISSUE THREAD

**Issue by suloman001** [SZtools/SZ-plugin#46]
how we can generate a slope unit I have one model for it and also generate a slope unit but with the boundary few areas are missing 
that are nor generate slope unit properly 
sir you have any model to generate a slope unit properly ?
Thanks

**Comment by giactitti** [comment]
Hi, sorry the plugin has not functions to generate slope unite. You can use r.slopeunit in GRASS GIS from Alvioli et al 2016
